# Generated by Django 5.2.8 on 2025-12-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("world", "World"),
                    ("uk", "UK"),
                    ("business", "Business"),
                    ("politics", "Politics"),
                    ("health", "Health"),
                    ("science", "Science"),
                    ("technology", "Tech"),
                    ("entertainment", "Entertainment"),
                    ("sport", "Sport"),
                ],
                default="world",
                max_length=20,
            ),
        ),
    ]
