# Generated by Django 5.2.8 on 2025-12-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("summary", models.TextField()),
                ("body", models.TextField()),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.CharField(max_length=100)),
                (
                    "score",
                    models.FloatField(help_text="Editorial score (accuracy, trust)"),
                ),
                (
                    "evidence",
                    models.TextField(
                        help_text="Supporting evidence, sources, fact-checks"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
