# Generated by Django 6.0.1 on 2026-02-01 16:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_publish_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LivingStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('semantic_centroid', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'living_stories',
            },
        ),
        migrations.CreateModel(
            name='PendingArticle',
            fields=[
                ('backend_article', models.OneToOneField(db_column='article_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pending_status', serialize=False, to='news.backendarticle')),
                ('source_domain', models.CharField(max_length=255)),
                ('vector_blob', models.JSONField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pending_articles_pool',
            },
        ),
        migrations.CreateModel(
            name='StoryUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article_ids', models.JSONField(help_text='List of BackendArticle IDs in this batch')),
                ('article_count', models.IntegerField(default=0)),
                ('batch_centroid', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='news.livingstory')),
            ],
            options={
                'db_table': 'story_updates',
            },
        ),
    ]
