#!/usr/bin/env bash
# Fetch secrets from a local HashiCorp Vault and render them to an env file suitable
# for systemd EnvironmentFile or run_with_env.sh overlay. Intended to be used as a
# pre-start step or a manual refresh command on developer machines.
#
# Requirements:
#   - vault CLI (apt install vault) and jq
#   - VAULT_ADDR exported or defaulting to http://127.0.0.1:8200
#   - role_id and secret_id stored in files (default /etc/justnews/vault_role_id and vault_secret_id)
#   - KV v2 path default: secret/justnews
#
# Security:
#   - Writes to /run/justnews/secrets.env by default (tmpfs, ephemeral)
#   - File created with mode 0640; ensure appropriate group permissions on /run/justnews

set -euo pipefail

export VAULT_ADDR="${VAULT_ADDR:=http://127.0.0.1:8200}"
: "${VAULT_ROLE_ID_FILE:=/etc/justnews/vault_role_id}"
: "${VAULT_SECRET_ID_FILE:=/etc/justnews/vault_secret_id}"
: "${VAULT_KV_PATH:=secret/justnews}"
: "${SECRETS_OUT:=/run/justnews/secrets.env}"

need_bin() {
  command -v "$1" >/dev/null 2>&1 || { echo "ERROR: required binary '$1' not found" >&2; exit 1; }
}

need_bin vault
need_bin jq

if [[ ! -r "$VAULT_ROLE_ID_FILE" || ! -r "$VAULT_SECRET_ID_FILE" ]]; then
  echo "ERROR: Missing role/secret id files: $VAULT_ROLE_ID_FILE $VAULT_SECRET_ID_FILE" >&2
  exit 1
fi

ROLE_ID="$(<"$VAULT_ROLE_ID_FILE")"
SECRET_ID="$(<"$VAULT_SECRET_ID_FILE")"

install -d -m 750 "$(dirname "$SECRETS_OUT")"

LOGIN_JSON="$(vault write -format=json auth/approle/login role_id="$ROLE_ID" secret_id="$SECRET_ID")"
TOKEN="$(jq -r .auth.client_token <<<"$LOGIN_JSON")"
if [[ -z "$TOKEN" || "$TOKEN" == "null" ]]; then
  echo "ERROR: Failed to obtain Vault token via AppRole" >&2
  exit 1
fi

SECRETS_JSON="$(VAULT_TOKEN="$TOKEN" vault kv get -format=json "$VAULT_KV_PATH")"
# Render KEY=VALUE lines, escaping newlines if any (simple case)
MAP_LINES="$(jq -r '.data.data | to_entries | map("\(.key)=\(.value)") | .[]' <<<"$SECRETS_JSON")"

# Write atomically
TMP_FILE="${SECRETS_OUT}.tmp$$"
{
  echo "# generated by fetch_secrets_to_env.sh from $VAULT_KV_PATH"
  echo "$MAP_LINES"
} >"$TMP_FILE"
install -m 640 "$TMP_FILE" "$SECRETS_OUT"
rm -f "$TMP_FILE"

echo "Wrote $SECRETS_OUT from Vault path $VAULT_KV_PATH"
